### ISSUE TITLE
question about AWS Lex resource with terraform 

### ISSUE THREAD

**Issue by nbmustafa** [jzbruno/terraform-aws-lex-examples#1]
This is an excellent example. but wondering if this is yet ready or not?

Curios to question this is just an example of how these resources will look like when the following three PRs are merged is that correct?
New Resource: aws_lex_intent #8917
New Resource: aws_lex_bot #8918
New Resource: aws_lex_bot_alias #8919

**Comment by jzbruno** [comment]
@nashvan Hello, I would recommend waiting until the other PRs are merged. After the review and merge of the slot type resource a few items were identified that need to be updated on the other PRs too. I am working this week to get them ready and with the help of the provider maintainers we should be able to get them reviewed and merged. 

I will update these examples to match the provider code too.

**Comment by nbmustafa** [comment]
@jzbruno brilliant, thank you very much, your contribution is really highly appreciated. please let (mention me if possible) when the PRs are merged and your templates are updated accordingly. thank you so much again.

**Comment by jzbruno** [comment]
@nashvan I have updated the examples here, not much changed. They still don't include a lambda integration example. But they work with the code in the "add_aws_lex_bot_alias" branch which should be close to the final version once all the PRs are merged.

**Comment by nbmustafa** [comment]
@jzbruno thank you very much, I am following every single commit you do on fixing these stuffs on the terraform provider, really well done. your contribution is highly appreciated by the entire community. thank you heaps.

**Comment by nbmustafa** [comment]
@jzbruno I was wondering if it would be doable within the upcoming PR if we can import intent messages from a json file?

**Comment by jzbruno** [comment]
@nashvan I would say to create a new issue. I would rather not delay this release. Finally getting traction after 2 years. :)

**Comment by nbmustafa** [comment]
@jzbruno  I garee with you. i will raise an issue later hopefully you can get on to that beside other three tracking issues you created. 

Brilliant work. Thanks again.

**Comment by jzbruno** [comment]
Looks like this is all merged and available in 3.10.0 of the provider. :)

**Comment by nbmustafa** [comment]
I created an issue on their for adding capability to import intents from json file. 
Thank you again. You have done a womderful job.
