### ISSUE TITLE
Getting regular expression issues

### ISSUE THREAD

**Issue by nbmustafa** [jzbruno/terraform-aws-lex-examples#3]
Hi @jzbruno 
I realised the regular expression issue, but now getting this 

aws_lex_slot_type.new_or_existing: Creating...
aws_lex_slot_type.optional_words: Creating...
aws_lex_slot_type.directional: Creating...
aws_lex_slot_type.product_actions: Creating...
aws_lex_slot_type.new_or_existing: Creation complete after 2s [id=abc_nash_develop_NewOrExisting]
data.aws_lex_slot_type.new_or_existing: Refreshing state...
aws_lex_slot_type.product_actions: Creation complete after 3s [id=abc_nash_develop_ProductActions]
data.aws_lex_slot_type.product_actions: Refreshing state...
aws_lex_slot_type.optional_words: Creation complete after 3s [id=abc_nash_develop_OptionalWords]
data.aws_lex_slot_type.optional_words: Refreshing state...
aws_lex_intent.action_banking: Creating...
aws_lex_slot_type.directional: Creation complete after 3s [id=abc_nash_develop_Directional]
data.aws_lex_slot_type.directional: Refreshing state...

Error: error creating intent abc_nash_develop_ActionBanking: BadRequestException: Resource 'abc_nash_develop_ActionBanking' should refer to immutable versions to create new version

**Comment by nbmustafa** [comment]
all good resolved this issue.

**Comment by jzbruno** [comment]
Hi @nashvan 

Sorry, for some reason thought i responded already. Glad to hear it is working now.
